- package.json
- src/index.ts
- src/infrastructure/logging/index.ts
- src/presentation/http/index.ts
- tsconfig.json
add esm support because it's recommended modern for `import`
> add esm support

- .editorconfig
- .vscode/settings.json
- src/index.ts
- src/presentation/api.interface.ts
- src/presentation/http/http-server.ts
- src/presentation/index.ts
- src/presentation/server.ts
1. Entry point shouldn't know about what presentation server is used, only about interface.
2. Presentation Server renamed to API
3. EditorConfig added
4. Spellcheck error fixed
> chore(naming): make presentation more clean

- src/presentation/http/router/oauth.ts
- src/repository/storage/postgres/orm/sequelize/index.ts
- The callback route will be opened in a popup by Web App
- So we just send tokens via a postMessage to the "opener" window 
- Then, close a window
> chore(oauth): use postmessage instead of cookies for oauth callback

- src/domain/service/note.ts
- src/domain/service/noteSettings.ts
- src/infrastructure/utils/hasProperty.ts
- src/presentation/http/fastify.d.ts
- src/presentation/http/http-api.ts
- src/presentation/http/middlewares/common/userIdResolver.ts
- src/presentation/http/middlewares/note/useNoteResolver.ts
- src/presentation/http/router/note.ts
- src/presentation/http/router/noteSettings.ts
- src/repository/note.repository.ts
- src/repository/noteSettings.repository.ts
- src/repository/storage/postgres/orm/sequelize/note.ts
- src/repository/storage/postgres/orm/sequelize/noteSettings.ts
Implemented a middleware that will convert public id to internal id.
Frontend uses note public id in all requests. Backend accepts note internal id in route handlers. So it will work with Domain services only by internal id.
This middleware does not set by default to all routes, and you need to pass it manually via "preHandler" options
> feat(router): note id resolver

- src/infrastructure/utils/empty.ts
- src/infrastructure/utils/notEmpty.ts
- src/presentation/http/decorators/forbidden.ts
- src/presentation/http/decorators/index.ts
- src/presentation/http/decorators/notAcceptable.ts
- src/presentation/http/decorators/notFound.ts
- src/presentation/http/decorators/unauthorized.ts
- src/presentation/http/fastify.d.ts
- src/presentation/http/http-api.ts
- src/presentation/http/middlewares/common/userIdResolver.ts
- src/presentation/http/middlewares/note/useNoteResolver.ts
- src/presentation/http/policies/authRequired.ts
- src/presentation/http/policies/index.ts
- src/presentation/http/policies/userInTeam.ts
- src/presentation/http/router/auth.ts
- src/presentation/http/router/note.ts
- src/presentation/http/router/noteSettings.ts
- src/presentation/http/router/oauth.ts
- src/presentation/http/router/user.ts
- src/repository/ai.repository.ts
- add `isEmpty` as well as `notEmpty` ---> to get rid of `!notEmpty()`
- added several reply decorators
- `reply.unauthorized()` — use when there is no user
- `reply.forbidden()` — use when we have user, but it has no access 
- `reply.notFound()` — someone requests a resource that we don't have
- `reply.notAcceptable()` — someone peforms some action on resource that was not found
- added a `userInTeam` policy for checking edit-note permission
- applied a `userInTeam` to `PATCH /node/<id>`
> chore(decorators): new reply decorators

- src/domain/service/noteList.ts
- src/presentation/http/router/noteList.ts
- src/repository/note.repository.ts
- src/repository/storage/postgres/orm/sequelize/note.ts
* added parameter for getNoteListByCreatorId func
* added portionSize constant for noteList in service
> feat(noteList):  added page parameter and portionSize constant

- .github/workflows/run-build-check.yml
- .github/workflows/run-eslint-check.yml
- .github/workflows/run-tests.yml
Fixed case, when github actions used to run twice after push to pull request. 
Now the workflows are triggered when pushing only to main branch.
In addition, now workflows won't be triggered when someone edit pull request (for example edit title).
> Fix multiple run of github action

- src/presentation/http/router/note.test.ts
- src/tests/test-data/notes-settings.json
- src/tests/test-data/notes.json
- tsconfig.json
- vitest.config.js
Testcases were written for the get note by id method
New data for tests were added to the test database
> Tests for get note by id

- src/presentation/http/router/note.test.ts
- src/presentation/http/router/note.ts
Added information about access rights to reply in get note by id method and in get note by custom hostname method.
For now, it only checks, if current user is creator of the note. 
Also, tests in note.test were changed because of new reply format.
> feat: notes access rights 

- src/tests/utils/setup.ts
Added `global.db.query()` helper that allows to execute sql statements in test DB. 
Such function will be helpful for [another pull request](https://github.com/codex-team/notes.api/pull/100), where we want to insert tomorrow date as expiration date for the session
> chore: global.db.query()

- src/presentation/api.interface.ts
- src/presentation/http/router/noteSettings.test.ts
- src/presentation/http/router/noteSettings.ts
- src/tests/test-data/notes-settings.json
- src/tests/test-data/notes.json
- src/tests/test-data/users.json
Added a schema to all methods to validate the id value. Also added some testcases and todos.
**GET note settings**:
- 200 status if note settings publicly available
- 400 status when public id has invalid characters
- 403 status public access is disabled
- 406 status when public id not exist
**GET team by public id** and **PATCH note settings by public id**:
- 200 status if note settings publicly available
- 400 status when public id has invalid characters
- 401 status when user is not authorized
- 406 status when public id not exist
> feat: note settings request validation for note settings

- migrations/tenant/0012-note-settings@add-invitation-hash.sql
- src/domain/entities/noteSettings.ts
- src/domain/service/noteSettings.ts
- src/infrastructure/utils/invitationHash.ts
- src/presentation/http/router/note.test.ts
- src/presentation/http/router/noteSettings.test.ts
- src/repository/storage/postgres/orm/sequelize/noteSettings.ts
- src/tests/test-data/notes-settings.json
- src/tests/utils/insert-data.ts
Added:
- tool, that generates invitation hash
- InvintationHash attribute to NoteSettings entity
- migration, that adds an invitation_hash column in note_settings table 
- invitation_hash field in test data 
Invitation hash is generated on note creation.
> Feat: invitation hash

- Dockerfile
- init.sh
- migrations/scripts/index.ts
- migrations/scripts/migrate.ts
- src/tests/utils/setup.ts
- tsconfig.json
2 migration scripts were moved to migration folder from /src/.
And Dockerfile was modified to COPY these scripts as well as configs and files they depend on.
Accepting any ideas / suggestions.
> Feat: Add migration scripts to deployment

- .github/workflows/send-test-results.yml
Make an api request to cancel workflow if all other flows were skipped/cancelled
> Change the way workflow stops

- src/presentation/http/router/auth.test.ts
- src/tests/test-data/user-sessions.json
- src/tests/utils/insert-data.ts
- 500 error raised if we started indexing of `user-sessions` test data with 1 because we used `global.db.query` method in test (id was 9999 and autoincrement sequence made minvalue 1 + 1, so we can't insert data with id 1).
- decided to insert `user-session` without id since it is not used anywhere, so that the id is generated using auto-increment
> fixed 500 error in auth tests

- src/presentation/http/router/note.test.ts
Test cases for the **DELETE /note/:notePublicId** route:
- status 200 if note was successfully deleted
- status 403 if the user is not the creator of the note
- status 401 if the user is not authorized
- status 406 if the note does not exist or has been deleted
- status 400 if notePublicId is incorrect
> сhore: delete note by id

- .github/workflows/send-test-results.yml
Now the message will look like this, which is a lot nicer imo:
👏 Checks triggered by GoldenJaden in
[Add a commit and a user who triggered the checks to the checks message](https://github.com/codex-team/notes.api/pull/211)
✅ [Build check](https://github.com/codex-team/notes.api/actions/runs/8123223136)
✅ [ESLint](https://github.com/codex-team/notes.api/actions/runs/8123223135)
✅ [API tests](https://github.com/codex-team/notes.api/actions/runs/8123223133)
Also, I deleted an overhead step about checking if all of the actions were cancelled / etc, because in real world it would _almost certainly_ never happen and it's just slowing down the pipeline
> Add a commit and a user who triggered the checks to the checks message

- package.json
- vitest.config.js
- yarn.lock
Added new module `@vitest/coverage-v8` for coverage testing.
Updated `yarn.lock`, updated `vitest.config.js`
Added new command `yarn coverage` to run tests and form a coverage report
> Add vitest coverage module and update config

- .github/workflows/run-tests.yml
- package.json
- vitest.config.js
- yarn.lock
Test coverage reports will now be commented on a corresponding PR.
I set the threshold to 80%, but we can change that.
It shows the percentage of code covered by tests and also compares your PR's coverage with the previous one (from the `main` branch)
> feat: Support for test coverage reports

- package.json
- vitest.config.js
- yarn.lock
closes #226 
Sometimes vitest failed to eliminate worker. To solve this, the tests are now run in non-threaded mode.
More about this issue: https://github.com/vitest-dev/vitest/issues/3077
> Fix: tests don't stop running in gh actions

- src/domain/entities/editorTools.ts
- src/domain/entities/notePublic.ts
- src/domain/entities/user.ts
- src/domain/service/ai.ts
- src/domain/service/noteList.ts
- src/domain/service/noteVisits.ts
- src/domain/service/shared/editorTools.ts
- src/domain/service/shared/index.ts
- src/domain/service/shared/note.ts
- src/domain/service/user.ts
- src/presentation/api.interface.ts
- src/presentation/http/http-api.ts
- src/presentation/http/router/ai.ts
- src/presentation/http/router/noteList.test.ts
- src/presentation/http/router/noteList.ts
- src/presentation/http/router/user.ts
- src/presentation/http/types/PolicyContext.ts
- src/repository/ai.repository.ts
- src/repository/storage/postgres/orm/sequelize/note.ts
- src/repository/storage/postgres/orm/sequelize/noteRelations.ts
- src/repository/storage/postgres/orm/sequelize/user.ts
- src/repository/team.repository.ts
- src/repository/transport/openai-api/index.ts
- src/repository/transport/openai-api/types/ApiResponse.ts
- src/repository/user.repository.ts
- src/tests/utils/database-helpers.ts
- src/tests/utils/setup.ts
- tsconfig.json
Current typescript compiler's module isn't validating that imports have explicit 'js' extensions.
Missing extensions can break the app.
Change the module to `node16`. Add missing extensions.
> Feat(TS): Change typescript compiler module

- src/presentation/http/router/note.ts
- Note visits are not saved, when user created the note
- Now on POST note endpoint noteVIsit saved
- left todo for event bus usage
> Save noteVisit on note creation

- package.json
- src/presentation/http/http-api.ts
- src/presentation/http/middlewares/note/useNoteResolver.ts
- src/presentation/http/router/upload.ts
- src/presentation/http/schema/Upload.ts
- yarn.lock
Added validation schemas for uploading file requests
> feat: added schemas for upload requests

- migrations/tenant/0031-note@add-tools-for-notes-that-do-not-have-ones.sql
We recently added tools field for `public.note` table, and now tools are inserted on appropriate routes
See #251 for more information
But old notes that were in table before tools field implementation are now having null in tools
Added migration that checks for note tools inside `content.blocks` of each note and adds appropriate array into `tools` field
> chore[migrations]: added migration for note data

- src/domain/service/note.ts
- src/presentation/http/router/note.test.ts
- src/presentation/http/router/note.ts
This creates a relation for an already existing note. We use it when we want to set parent note for an existing note. 
Also, tests added for this route
> Feature: Add POST  /note/:notePublicId/relation route

- .gitignore
- src/domain/entities/note.ts
- src/domain/entities/notePublic.ts
- src/presentation/http/router/noteList.test.ts
- src/presentation/http/schema/Note.ts
- src/repository/index.ts
- src/repository/object.repository.ts
- src/repository/storage/postgres/orm/sequelize/note.ts
1. added `/s3` folder to .gitignore
2. Added optional property `cover` to `Note` entity
3. Added `noteSettings` to `NoteModel`
> feat: added cover to note list

- src/presentation/http/router/note.test.ts
- src/presentation/http/schema/Note.ts
To display some fields in note settings we need to know, when was note updated
Whats done:
- Added fields createdAt and updatedAt to note schema
Result: We get fields createdAt and updatedAt in response with note
> feat: return fields updatedAt and createdAt with note

- src/domain/index.ts
- src/domain/service/fileUploader.service.ts
- src/domain/service/noteSettings.ts
- src/domain/service/shared/fileUploader.ts
- src/domain/service/shared/index.ts
- src/presentation/http/router/noteSettings.test.ts
- src/repository/file.repository.ts
- src/repository/object.repository.ts
- src/repository/storage/postgres/orm/sequelize/file.ts
- src/repository/storage/s3/index.ts
- src/tests/utils/database-helpers.ts
removing previous image while patching note cover
> feat: delete previous cover after updating

- src/domain/entities/team.ts
- src/domain/service/note.ts
- src/domain/service/noteSettings.ts
- src/domain/service/shared/note.ts
- src/presentation/http/router/join.test.ts
- src/presentation/http/router/join.ts
- src/repository/storage/postgres/orm/sequelize/teams.ts
- src/repository/team.repository.ts
This PR is related to join route usage on web side (it should not know noteInternalId which now returns on join route)
- added `TeamMemberPublic` entity (team member without team relation id and with `notePublicId` as noteId)
- added shared service method for getting public noteId by NoteInternalid
- made join route return TeamMember with public noteId
- patched repository function
* isUserTeamMember() method deprecated
* Now we can use getTeamMemberByNoteAndUserId because it uses same storage logic (we can check teamMember that we got on null just in domain service)
- get rid of the result : {} decoration in /join route
> chore(team): Implemented public team member

- migrations/tenant/0032-note-history@add-note-history-table.sql
- src/domain/entities/noteHistory.ts
- src/domain/index.ts
- src/domain/service/note.ts
- src/domain/service/noteSettings.ts
- src/presentation/http/http-api.ts
- src/presentation/http/router/note.test.ts
- src/presentation/http/router/note.ts
- src/presentation/http/schema/History.ts
- src/repository/index.ts
- src/repository/noteHistory.repository.ts
- src/repository/storage/noteHistory.storage.ts
- src/repository/storage/postgres/orm/sequelize/note.ts
- src/repository/storage/postgres/orm/sequelize/noteHistory.ts
- src/repository/storage/postgres/orm/sequelize/user.ts
- src/repository/team.repository.ts
- src/tests/utils/database-helpers.ts
For now we can complitely grind all note (on web) just by highliting full note and pressing any character
We need to be able to check note content history and get back to the content that was actual some time ago
- now service adds new history record on note creation
- now service checks if content changes are valuable enough compared to latest saved history
public noteHistory has `notePublic` id instead of `NoteInternalId`
- now we can get full note history meta of the note (for displaying in note history as a list of changes)
- now we can get certain history record with content and display it as a version of the note
tests cover states
- Unauthorized user
- User is not in team
- Changes are not valuable for note history record creation
- Changes are valuable enough for saving new …
> feat(noteHistory): note history implementation

- migrations/tenant/0033-note-history@add-initial-note-history-records-for-notes.sql
Now for old notes there are no history records, so user can not patch them
Added converter that will add note history records for notes, that does not have them
> chore(note-history): Add converter for note history

- migrations/tenant/0035-note-teams@add-unique-index-on-note-and-user-id.sql
- src/presentation/http/router/noteSettings.test.ts
- src/repository/storage/postgres/orm/sequelize/teams.ts
- if we add unique key constraints then it won't allow duplicate entry.
- This PR adds unique index on note and user id of teams model described in Issue Closes #285
> fix: adds unique index on note and user id of teams table

- src/presentation/http/router/note.test.ts
- src/presentation/http/schema/Note.ts
Now you can send creatorId field from  database to use it in frontend. This solves #283.
> feat: New field in Note's schema
