package-lock.json, package.json, src/infrastructure/logging/index.ts, src/presentation/http/index.ts, tsconfig.json
implement path aliases for better readability
=> implement path aliases

app-config.yaml, package-lock.json, package.json, src/infrastructure/config/index.ts, src/infrastructure/jwt/index.ts, src/presentation/http/http-server.ts
Added infrastructure service `JwtService` to work with JWT tokens
=> Added infrastructure service to work with jwt tokens

app-config.yaml, package-lock.json, package.json, src/domain/service/note.ts, src/index.ts, src/infrastructure/config/index.ts, src/presentation/http/http-server.ts, src/presentation/http/router/note.ts, src/presentation/http/types/HttpResponse.ts, src/repository/note.repository.ts, src/repository/storage/postgres/orm/sequelize/note.ts
1. Added `GET` note by id endpoint
2. Added getNoteById to service
3. Added getNote to repository
4. Added getNote to stotage
=> Added get note endpoint

src/presentation/http/http-server.ts, src/presentation/http/middlewares/auth.ts, src/presentation/http/middlewares/index.ts, src/presentation/http/router/note.ts
1. Added auth middle, which checks is access token provided
2. Passed middleware to note router
=> Added base for auth middleware

src/presentation/http/http-server.ts
=> Fixed image building

src/domain/entities/note.ts, src/domain/entities/user.ts, src/domain/index.ts, src/domain/service/user.ts, src/presentation/http/http-server.ts, src/presentation/http/router/oauth.ts, src/repository/index.ts, src/repository/storage/postgres/orm/sequelize/user.ts, src/repository/transport/fetch.transport.ts, src/repository/transport/google-api/index.ts, src/repository/transport/google-api/types/ApiResponse.ts, src/repository/transport/google-api/types/GetUserInfoResponsePayload.ts, src/repository/user.repository.ts
1. Added methods to get and insert user to `user.storage`
2. Added user repository with `getUserByProvider`, which gets user info from provider and saves it to storage
3. Added user service
4. Added user service to oauth router
=> Add methods to user storage, added user repository, user service

package-lock.json, package.json, src/domain/index.ts, src/domain/service/auth.ts, src/domain/service/note.ts, src/domain/service/user.ts, src/fastifyOAuth.d.ts, src/infrastructure/logging/index.ts, src/presentation/api.interface.ts, src/presentation/http/http-server.ts, src/presentation/http/middlewares/auth.ts, src/presentation/http/middlewares/index.ts, src/presentation/http/router/note.ts, src/presentation/http/router/oauth.ts, src/presentation/http/types/HttpRequestContext.ts, src/presentation/http/types/HttpResponse.ts, src/repository/index.ts, src/repository/note.repository.ts, src/repository/storage/postgres/orm/sequelize/index.ts, src/repository/storage/postgres/orm/sequelize/note.ts, src/repository/storage/postgres/orm/sequelize/user.ts, src/repository/storage/postgres/orm/sequelize/userSession.ts, src/repository/transport/google-api/index.ts, src/repository/transport/google-api/types/ApiResponse.ts, src/repository/user.repository.ts, src/repository/userSession.repository.ts
Eslint Config CodeX updated to the latest version.
Autofix
=> chore(eslint): autofix

src/repository/index.ts, src/repository/storage/postgres/orm/sequelize/user.ts, src/repository/storage/postgres/orm/sequelize/userSession.ts
Fixed launching app. Made UserSession storage init after User
=> Make UserSession storage init after User

.gitignore, package-lock.json, package.json, src/presentation/http/http-server.ts
Added a bit of openapi codegeneration
=> Added fastify-swagger as automatic route parser

app-config.yaml, src/domain/entities/auth.ts, src/domain/entities/authSession.ts, src/domain/index.ts, src/domain/service/auth.ts, src/infrastructure/config/index.ts, src/presentation/http/http-server.ts, src/presentation/http/router/auth.ts, src/presentation/http/router/oauth.ts, src/repository/index.ts, src/repository/storage/postgres/orm/sequelize/note.ts, src/repository/storage/postgres/orm/sequelize/user.ts, src/repository/userSession.repository.ts
1. Added route for regenerating tokens
2. Added sessions logic
3. Added generating access and refresh in google oauth route
=> Auth implemented

src/presentation/http/router/auth.ts
1. Added auth/logout route, which removed session by refresh token
=> Added logout

app-config.yaml, package-lock.json, package.json, src/infrastructure/config/index.ts, src/presentation/http/http-server.ts, src/presentation/http/router/oauth.ts
1. Added setting tokens to cookies in oauth router
2. Redirect after auth
=> Added setting tokens to cookies in oauth, added redirecting to referer

src/domain/service/user.ts, src/presentation/http/http-server.ts, src/presentation/http/router/user.ts, src/repository/user.repository.ts
Get user by it's id from the context
=> Added user router

app-config.yaml, src/domain/index.ts, src/domain/service/ai.ts, src/infrastructure/config/index.ts, src/presentation/http/http-server.ts, src/presentation/http/router/ai.ts, src/repository/ai.repository.ts, src/repository/index.ts, src/repository/transport/fetch.transport.ts, src/repository/transport/openai-api/index.ts, src/repository/transport/openai-api/types/ApiResponse.ts, src/repository/transport/openai-api/types/GetCompletionResponsePayload.ts
Added new POST `/ai/complete` endpoint which expects `content` parameter containing the text to be completed by ai
=> Add AI completion endpoint

src/domain/entities/notesSettings.ts, src/domain/entities/publicId.ts, src/domain/service/note.ts, src/fastifyOAuth.d.ts, src/presentation/http/middlewares/auth.ts, src/presentation/http/middlewares/authRequired.ts, src/presentation/http/middlewares/index.ts, src/presentation/http/middlewares/withUser.ts, src/presentation/http/router/note.ts, src/presentation/http/router/oauth.ts, src/presentation/http/router/user.ts, src/repository/note.repository.ts, src/repository/storage/postgres/orm/sequelize/note.ts, src/repository/storage/postgres/orm/sequelize/notesSettings.ts
1. Changed Auth middleware
2. Added public id and enable options to note setting
3. Added public id and enable logic to note route
=> Added note public id and enabled attributes to note settings

src/presentation/http/router/auth.ts, src/presentation/http/router/note.ts, src/presentation/http/router/user.ts, src/repository/storage/postgres/orm/sequelize/note.ts
1. Fixed interfaces usage
2. Fixed middlewares
3. Made auth router REST
=> Fixed imports, miidlewares usage

src/presentation/http/router/note.ts
=> Changed create note options to body

src/repository/index.ts
Make user storage creating before note
=> Fix storages creating

src/domain/service/note.ts, src/presentation/http/middlewares/authRequired.ts, src/presentation/http/router/note.ts, src/repository/note.repository.ts, src/repository/storage/postgres/orm/sequelize/note.ts
=> Added ability to update notes settings

.vscode/settings.json, src/index.ts, src/infrastructure/metrics/index.ts, src/infrastructure/utils/notEmpty.ts, src/presentation/http/http-server.ts, src/presentation/http/middlewares/authRequired.ts, src/presentation/http/middlewares/withUser.ts, src/presentation/http/router/auth.ts, src/presentation/http/router/note.ts, src/presentation/http/router/oauth.ts, src/repository/ai.repository.ts, src/repository/storage/postgres/orm/sequelize/user.ts
The #53 has eslint config update introducing new alerts. This PR resolves them.
=> fix(eslint): new eslint errors resolved

.eslintrc, src/presentation/http/decorators/notFound.ts, src/presentation/http/fastify.d.ts, src/presentation/http/http-server.ts, src/presentation/http/middlewares/authRequired.ts, src/presentation/http/router/auth.ts, src/presentation/http/router/note.ts, src/presentation/http/router/oauth.ts, src/presentation/http/router/user.ts, src/presentation/http/schema/User.ts, src/presentation/http/schema/index.ts, src/presentation/http/types/HttpResponse.ts
- notFound decorator added. Simplifies 404 responses.
- Schema for request body validation added. UserSchema is described as an example. Useful for [validation and serialization](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization)
- 'data' wrapper removed from responses. It has no sense.
- Do not cast response types, use "Reply" generic instead.
- Errors format improved. Send HTTP status code via response status. Send "code" and "message" describing business-logic in body
=> chore(fastify): router handlers updated

package-lock.json, src/presentation/http/http-api.ts
1. Reorder Fastify plugins to respect documentation
2. Add missed package-lock.json
=> chore(fastify): reorder plugins

src/presentation/http/http-api.ts, src/tests/utils/insert-data.ts
- Fixes eslint problems introduced in #78 
- Fixes note_settings new table named introduced in #59
=> fix: eslint

src/presentation/http/router/note.ts, src/presentation/http/schema/Note.ts
1. PATCH `/note` changed to PATCH `/note/<id>`
2. Note Schema simplified
3. Get rid of redundant interfaces
=> feat(note): edit note api fixed

src/presentation/http/router/noteSettings.ts
=> fix: fixed note settings patch

yarn.lock
=> fix: fixed yarn.lock

src/presentation/http/fastify.d.ts, src/presentation/http/middlewares/note/useNoteResolver.ts, src/presentation/http/middlewares/noteSettings/useNoteSettingsResolver.ts, src/presentation/http/policies/checkPermissions.ts, src/presentation/http/policies/index.ts, src/presentation/http/policies/notePublicOrUserInTeam.ts, src/presentation/http/router/note.ts, src/presentation/http/router/noteSettings.ts
1. Added note settings resolver middleware, which pass note settings using note id
2. Added checkPermission policy
=> feat: added permission policy

migrations/tenant/0007-editor-tools@rename-columns.sql
Rename columns & add isDefault column
=> chore: add migration

app-config.yaml, src/domain/service/note.ts, src/presentation/http/router/note.ts, src/repository/note.repository.ts, src/repository/storage/postgres/orm/sequelize/note.ts
added route to delete note by id.
some minor comment fixes
=> feat(note): implement deleteNoteById 

.github/workflows/run-tests.yml
Added workflow that runs tests after each pull request
=> Added github action to run tests

src/domain/index.ts, src/domain/service/editorTools.ts, src/domain/service/shared/README.md, src/domain/service/shared/editorTools.ts, src/domain/service/shared/index.ts, src/domain/service/user.ts, src/presentation/http/router/user.ts, src/repository/editorTools.repository.ts, src/repository/note.repository.ts, src/repository/storage/postgres/orm/sequelize/editorTools.ts
- Business Logic (tools merging) moved from Presentation to Domain Level
- Introduced `Shared Domain Methods` — simple way to decouple domains
=> chore: move bis-logic from ui do domain, decouple domains

src/tests/README.md, src/tests/utils/setup.ts
- new Globally exposed method for creating accessToken using id (global.auth)
=> feat(tests) : auth method added

.github/workflows/run-build-check.yml, .github/workflows/run-eslint-check.yml, .github/workflows/run-tests.yml, .github/workflows/send-test-results.yml
Changed bot webhook to the right one. 
Renamed action names.
Fixed composite workflow call's metadata.
=> Fix: added file extension and metadata in step

docs/inheritance-policy.md
- added docs directory
- added doc for inheritance policy
=> feat: docs directory added

migrations/tenant/0010-note-relations@add-note-relations-table.sql
- added migration for adding note_relations table
=> [feat] added migration for note_relations table

migrations/tenant/0011-teams@add-teams-table.sql
- added migration for adding teams table
=> [feat] added migration for teams table

src/presentation/http/router/user.test.ts, src/tests/test-data/users.json
- created tests for `/user/myself` endpoint
- added photo field to users test data
=> [chore]: test for `/user/myself` endpoint

src/domain/service/note.ts, src/domain/service/noteSettings.ts
Fixed incorrect import of DomainError file to make prod work again
=> Fix file DomainError import

src/domain/service/note.ts, src/presentation/http/router/note.test.ts, src/repository/noteRelations.repository.ts, src/repository/storage/postgres/orm/sequelize/noteRelations.ts, src/tests/test-data/notes-relations.json, src/tests/test-data/notes-settings.json, src/tests/test-data/notes.json
Added function to delete note relationships and test to it
=> feat: child parent relationship, delete func

src/domain/service/user.ts, src/presentation/http/router/user.ts, src/repository/storage/postgres/orm/sequelize/user.ts
1. Fixed adding user editor tool
2. Added route to remove editor tool
=> feat: added ability to remove user editor tool

src/presentation/http/middlewares/note/useNoteResolver.ts, src/presentation/http/middlewares/noteSettings/useMemberRoleResolver.ts, src/presentation/http/middlewares/noteSettings/useNoteSettingsResolver.ts, src/presentation/http/policies/authRequired.ts, src/presentation/http/policies/userCanEdit.ts, src/presentation/http/router/note.ts
=> Fix imports

src/presentation/http/router/note.test.ts
Rewrite testcases for deleting note enpoint in the new manner
=> Refactor DELETE note tests 

src/presentation/http/router/join.test.ts, src/presentation/http/router/noteSettings.test.ts, src/tests/utils/database-helpers.ts
chore - updated desctiption
chore - made now user.name, user.email, note.publicId optional
=> chore(tests): user.name, user.email, note.publicId parametes in database helpers are optional

src/presentation/http/router/noteList.test.ts, src/presentation/http/router/user.test.ts
Rewrite GET noteList and user tests in the new manner
=> refactor(tests): GET user and GET noteList

src/presentation/http/router/note.test.ts
now PATCH and POST /note are corresponding to actual test model
=> Refactor PATCH and POST note tests

migrations/tenant/0020-editor-tools@add-author.sql, migrations/tenant/0021-editor-tool@add-auto-increment.sql, src/domain/entities/editorTools.ts, src/domain/service/editorTools.ts, src/presentation/http/router/editorTools.test.ts, src/presentation/http/router/editorTools.ts, src/presentation/http/router/user.test.ts, src/presentation/http/router/user.ts, src/presentation/http/schema/EditorTool.ts, src/repository/editorTools.repository.ts, src/repository/storage/postgres/orm/sequelize/editorTools.ts, src/tests/utils/database-helpers.ts
1. Added migrations for author tool field
2. Added migration for autoincrementing tool id
3. Fixed creating tool, removed hash id
4. Added tests for adding tool
=> feat: added test for adding tool, fixed adding tool

src/presentation/http/schema/User.ts, src/repository/storage/postgres/orm/sequelize/user.ts, src/repository/user.repository.ts
- user.editor-tools can not be null
=> fix(user): user schema error fixed

migrations/tenant/0022-user@editor-tools-null-to-empty-array.sql
user.editorTools could not be null
=> fix(migratinons): user.editorTools null to '[]'

migrations/tenant/0023-note-relations@add-auto-increment.sql
Add migration that creates autoincrement on note-relations table
=> Add note relations autoincrement

src/presentation/http/router/note.test.ts, src/presentation/http/router/note.ts, src/presentation/http/router/noteSettings.test.ts, src/presentation/http/schema/Note.ts
Finished refactoring tests for team rights. Now it's done via `test.each` method.
=> Refactor tests for team rights in note.ts

package.json, src/index.ts, src/infrastructure/config/index.ts, src/repository/index.ts, src/repository/storage/s3/index.ts, src/tests/utils/setup.ts, yarn.lock
1. Added s3 storage
2. Added s3 storage options to config
=> feat(file-uploader): added base for s3 storage

migrations/tenant/0025-files@add-files-table.sql, src/domain/entities/file.ts, src/repository/index.ts, src/repository/storage/file.storage.ts, src/repository/storage/postgres/orm/sequelize/file.ts
1. Added file model in database
2. Added file domain entity
=> feat(file-uploader): added file model and file domain entity

src/domain/service/fileUploader.service.ts
=> fix(file uploader): fixed some import typo

src/domain/entities/note.ts, src/domain/service/editorTools.ts, src/domain/service/note.ts, src/presentation/http/http-api.ts, src/presentation/http/router/note.test.ts, src/presentation/http/router/note.ts, src/repository/editorTools.repository.ts, src/repository/storage/postgres/orm/sequelize/editorTools.ts, src/tests/utils/database-helpers.ts
Add note tools data to GET `/note/id` and GET `/note/resolve-hostname/hostname` responses
=> feat(note): Add tools to GET /note/id and GET /note/resolve-hostname/hostname

app-config.yaml, package.json, src/infrastructure/config/index.ts, src/repository/storage/s3/index.ts, src/tests/utils/s3-helpers.ts, src/tests/utils/setup.ts, yarn.lock
We need to test file uploader, which requires s3 storage
1. Added testcontainers library to work with s3 storage
2. Added s3 to tests setup
3. Added S3Helpers, which contains methods for creating buckets for testing
=> feat(file-uploader): added base for s3 testing

src/presentation/http/router/noteSettings.test.ts, src/presentation/http/router/noteSettings.ts, src/tests/utils/database-helpers.ts
Added ability to patch cover field in note settings
=> feat: added cover to patch note settings

app-config.yaml, docker-compose.yml, package.json, src/infrastructure/utils/streamToBuffer.ts, src/repository/storage/s3/index.ts, yarn.lock
Migrated from aws-sdk v2 to v3
=> feat: migrate to aws-sdk v3

src/domain/service/note.ts, src/presentation/http/router/note.test.ts, src/repository/noteHistory.repository.ts, src/repository/storage/postgres/orm/sequelize/noteHistory.ts
Now we can not delete note previously not deleted noteHistory
because we have fk constraint in note history table related to noteId
Delete note history on note deletion
=> chore(noteHistory): Delete note history on note deletion

migrations/tenant/0034-note-history@change-created-at-type-and-convert-data.sql, src/domain/entities/noteHistory.ts, src/domain/service/note.ts, src/repository/noteHistory.repository.ts, src/repository/storage/postgres/orm/sequelize/noteHistory.ts
- Now history dates would be stored with timezone and will be displayed correctly
- Now history meta would be returned in correct order (with descending order by created_at)
- Added `historyView` entity that presents historyRecord with user info
=> chore(note-history): Changed created_at field of the note_history table

src/repository/storage/postgres/orm/sequelize/noteVisits.ts
**Problem**:
noteid is pointing to users table and userid pointing to notes table.
**Solution**
nodeid should be pointing to notes table and userid to users table
=> FIX: Note visit relation fix
